apiVersion: v1
kind: Service
metadata:
  name: project-fundata-service
  labels:
    app: project-fundata
spec:
  selector:
    app: project-fundata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP